"version 330 core\n"
"layout (location = 0) in vec3 aPos;\n"
"layout (loaction = 1) in vec2 aTexCoord;\n"
"uniform vec3 colorMulitpler;\n"
"uniform mat4 model;\n"
"uniform mat4 view;\n"
"uniform mat4 projection;\n"
"out vec2 TexCoord;\n"	
"out vec4 vertexColor;\n"
"void main()\n"
"{\n"
"   gl_Position = projection * view * model * vec4(aPos, 1.0f);\n"
"   TexCoord = aTexCoord;\n"
"   vertexColor = vec4(colorMulitpler, 1.0f);\n"
"}\0";